### ISSUE TITLE
Training code (train_lang2vec)

### ISSUE THREAD

**Issue by maulikmadhavi** [swshon/arabic-dialect-identification#1]
Hi Suwon Shon

I am trying to run training script in last few days. I could not run it. As it shows the following error:
```
Traceback` (most recent call last):
  File "scripts/train_lang2vec.py", line 232, in <module>
    if c[iter,0]>MAX_INPUT_LENGTH:
IndexError: too many indices for array
```
I think ``c`` should be replaced by ``temp_shapes``. However, by doing so we trapped in model divergence problem (line 246-248) as loss_v becomes NaN.

Please help. 
Thanks

**Comment by swshon** [comment]
Hi. I updated code and also revised a few minor errors. 

Thanks.
